apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
